version: '3'
services:
  mongo:
    image: mongo
    ports:
    - 21027:21027
  redis:
    image: redis
    ports:
    - 6379:6379
  screeps:
    image: screepers/screeps-launcher-node
    build: .
    environment:
      REDIS_HOST: redis
      MONGO_HOST: mongo
    volumes:
    - ./test:/screeps
    ports:
    - 21025:21025
    - 21026:21026
    